services:
  - type: web
    name: AI-Interviewer-Pro
    runtime: python
    rootDir: ai interviewer chatbot/backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9